### ISSUE TITLE
"Form is incomplete!" Error on installation

### ISSUE THREAD

**Issue by rileyjalexander** [coinables/Blockchain-Receive-Payments-API-Shopping-Cart#1]
Cart works, admin works, I was able to add products with no issues in admin, I can add them to my shopping cart, I then enter all my details (email, address, state, etc) and click submit and it says the form is incomplete.

So basically, the validation ins't working for some reason, OR the session is not picking up the data entered so the validation thinks it is empty. Any ideas?

**Comment by coinables** [comment]
Thanks for letting me know. I just made a commit to fix the error. The only file you'll need to update is the checkout.php page and it should work.
