### ISSUE TITLE
Cannot Read QR Code

### ISSUE THREAD

**Issue by rileyjalexander** [coinables/Blockchain-Receive-Payments-API-Shopping-Cart#2]
On Pay.php, my mobile wallet cannot read the QR Code (both Copay and Blockchain)

It says "Could not recognize valid bitcoin qr code"

It is also not showing up the raw address inside the text box like I see it is supposed to. 

Seems that

`<?php echo $_SESSION['payTo']; ?>`

Contains no data, so the qr code has no data, and hence, input box has no data. 

Thanks for your help and corrections in code!

**Comment by rileyjalexander** [comment]
Completely re-installed fresh source to ensure that there wasn't any issue on my end and still ended up  with the same results so there is definitely a issue with code. Thank you in advance for looking into a solution. Can't wait to get this live :)

**Comment by coinables** [comment]
I am unable to recreate this error. It's likely an issue trying to initiate the handshake with blockchain.info. 
Make sure your config.php file is filled out correctly (api key, xpub, root url, etc).

I made a video that should help getting set up with their receive payments API: https://www.youtube.com/watch?v=ASCz5uLs5EE

If the video doesn't help you can also try to debug what's going on.

Save the below code as a php file and run it in the same folder that you have all the files for this project.  Tell me what it happens.  

**debug.php**

```
<?php
require_once('config.php');
$orderID = 1;

//call blockchain info receive payments API
    $callback_url = $rootURL."/callback.php?invoice=".$orderID."&secret=".$secret;
    $receive_url = "https://api.blockchain.info/v2/receive?key=".$api_key."&xpub=".$xpub."&callback=".urlencode($callback_url);
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_URL, $receive_url);
    $ccc = curl_exec($ch);
    $json = json_decode($ccc, true);
        var_dump($json);
?>
```

**Comment by rileyjalexander** [comment]
For some reason when I entered the XPub, I had an extra " in the field. Thanks for helping me troubleshoot and find the issue!
