### ISSUE TITLE
Unknown error 1146

### ISSUE THREAD

**Issue by xunorus** [coinables/Blockchain-Receive-Payments-API-Shopping-Cart#4]
HI Coinables, Thanks for your amazing work. 
Im cant manage to run the store in local. Im on last ubuntu, have tried using Lampp, Xampp, and manual steps to install diferent server versions with the db.

I created the db in phpmyadmin, it works, but when I run the site I get 

Unknown error 1146

Im stuck here!, I searched a lot and In an act of despair Im trying to get your feedback ...

Thanks in advance

**Comment by coinables** [comment]
Does it say anything else? This sounds like an issue with your database setup. 1146 is table does not exist, did you import the database file from this repo to your db?

**Comment by xunorus** [comment]
Yep!  I didnt imported the database file... so found a workaround and managed to enter mysql console (im a newbie) and executed each line manually, then it worked! 
I was having the same issue though (1146 error), and It fixed when I specified  the database name with the command:
USE my_db_name;

It may be an obvious thing  but this note may also help another newbie around...
Im researching your amazing work, thank so much!
