### ISSUE TITLE
Blockchain API Request

### ISSUE THREAD

**Issue by michaelsomerville** [coinables/Blockchain-Receive-Payments-API-Shopping-Cart#6]
Hey, 
This is a great application and thanks for taking the time - it's exactly what I was looking for to help me understand this a little more. One thing though, how the heck do you get approved with blockchain api. They have denied me 3 times now

**Comment by coinables** [comment]
It is very difficult to get an API key from them these days. Keep an eye on my version tangerine.pw easy to sign up and will have shopping cart integration. You can sign up now, but not launching until next month. Other alternatives include block.io, blockcypher, blocktrail, and blockonomics.

**Comment by michaelsomerville** [comment]
I guess they want serious user only, which is strange in the current community. The issue I have with those sites, ie. block.io / gourl.io etc - they are so low level on the UI and stuff. It's scary to me. lol

**Comment by michaelsomerville** [comment]
I am just learning all this stuff, but moving fast, don't have experience outside of PHP and some JS. Do you think sites like gourl.io / coinpayments.net are just using the json to see if a payment was made to that address ? gourl.io says they generate an address and only allow 3 transactions. They had fiat to the amount to track it. lol

**Comment by Beetario** [comment]
Perdí recientemente más de 300usd con esta librería https://github.com/coinables/Bitcoin-NoAPI-Shopping-Cart 
Ahora usando esta librería también perdí 10 usd, también se encuentra vulnerable, no usar!
