### ISSUE TITLE
Change to BTC only

### ISSUE THREAD

**Issue by Jonesyj83** [coinables/Blockchain-Receive-Payments-API-Shopping-Cart#7]
Got items on my site which is set to a fixed BTC amount, is there a way to add this?

**Comment by Itcoinbaycom** [comment]
I have the exact same issue. Just bought your book but sort of in a rush to get this implemented so if you are for hire... 

Got my API Key and Xpub set up and copied your store files but all I need to do is eliminate any reference to $$$. My customers need to see an item priced in BTC, add it to the cart and see the price in BTC and then checkout and pay in BTC. Seems like this would be easier but I am new to all of this so it is a bit overwhelming at the moment.

Any help would be greatly appreciated! Like I said, I will gladly pay you to set this up for me if you're for hire.

Thanks!

**Comment by coinables** [comment]
Yes I can make the change to BTC only but I'm short on time lately. Maybe tonight or this Sunday I'll upload as a new repo since I don't have the time to add it as a feature.

**Comment by coinables** [comment]
I have made the changes to BTC only and pushed it to a new branch for testing. Can someone test and report back?     

https://github.com/coinables/Blockchain-Receive-Payments-API-Shopping-Cart/tree/PRICE_FIXED_IN_BTC

**Comment by Itcoinbaycom** [comment]
Man that would be awesome! Thank you very much in advance and please  
and tell me what I owe you. I understand you must be short on time. I  
think I mentioned I bought your book. I can put a link and or a thank  
you to you on my web site as well if you'd like.


Quoting Kyle Honeycutt <notifications@github.com>:

**Comment by Itcoinbaycom** [comment]
I will try to test it tomorrow if I have time. Thank you so much for doing this and especially so quickly!!!

**Comment by coinables** [comment]
You don't owe anything. Thank you for helping test and contribute to open source bitcoin software. The more of us, the better.

**Comment by Itcoinbaycom** [comment]
Man really awesome, thanks again. Here is my website I'm trying to  
build: https://itcoinbay.com/. And here is as far as I got with your  
routine: https://itcoinbay.com/paymemberfee/

Still not there yet but you will help me make a big stride with this  
code. There are lots of issues with the theme, the main one being that  
it doesn't let you choose Bitcoin, or any other crypto, as a currency.  
But I'm scheduled for a Skype call with the theme author on Friday and  
hope to get this resolved soon. I hope this site can help add to the  
momentum, at least in a small way.

Quoting Kyle Honeycutt <notifications@github.com>:

**Comment by Itcoinbaycom** [comment]
Tested it Kyle and works like a charm. Thank you so much! You're the MAN.
